import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import {spawnSync} from 'node:child_process';
import {artifactFields} from '../scripts/artifact-schema.mjs';
const scripts=path.resolve('scripts');
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'arch-contract-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));return root;}
function write(root,rel,text){const file=path.join(root,rel);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,text);}
function run(root,script,...args){return spawnSync(process.execPath,[path.join(scripts,script+'.mjs'),...args],{cwd:root,encoding:'utf8'});}
const sheet=fields=>'## Ficha arqueológica\n\n| Campo | Registro |\n|---|---|\n'+fields.map(([field])=>`| **${field}** | Valor de ${field} com [[Destino\\|alias]] |`).join('\n')+'\n\n## Referências\n\nTexto preservado.\n';
const seven=new Set(['Promessa','Futuro prometido','Futuro produzido','Quando a promessa virou expectativa','Futuro tornado mais provável','Descendentes possíveis','Novo problema produzido pelo sucesso']);
test('33 campos preservados; migração gera proposta sem escrever e é idempotente',t=>{const root=fixture(t),before='Abertura intacta.\n\n'+sheet(artifactFields);write(root,'03 artefatos/Teste.md',before);assert.equal(run(root,'migrate-artifact-sheets').status,0);assert.equal(fs.readFileSync(path.join(root,'03 artefatos/Teste.md'),'utf8'),before);const manifest=JSON.parse(fs.readFileSync(path.join(root,'.review/migrate-artifact-sheets/manifest.json')));assert.equal(manifest.changes.length,0);});
test('26 campos recebem apenas sete linhas; todos valores e narrativa permanecem',t=>{const root=fixture(t),before='Abertura intacta.\n\n'+sheet(artifactFields.filter(([field])=>!seven.has(field)));write(root,'03 artefatos/Teste.md',before);assert.equal(run(root,'migrate-artifact-sheets').status,0);assert.equal(fs.readFileSync(path.join(root,'03 artefatos/Teste.md'),'utf8'),before);assert.equal(run(root,'migrate-artifact-sheets','--apply').status,0);const after=fs.readFileSync(path.join(root,'03 artefatos/Teste.md'),'utf8');assert.equal(after.split('\n').length-before.split('\n').length,7);for(const line of before.split('\n'))assert.ok(after.includes(line));assert.equal(run(root,'migrate-artifact-sheets').status,0);assert.equal(JSON.parse(fs.readFileSync(path.join(root,'.review/migrate-artifact-sheets/manifest.json'))).changes.length,0);});
test('proposta obsoleta não pode sobrescrever uma revisão posterior',t=>{const root=fixture(t);write(root,'03 artefatos/Teste.md',sheet(artifactFields.slice(0,26)));assert.equal(run(root,'migrate-artifact-sheets').status,0);write(root,'03 artefatos/Teste.md','Revisão posterior');assert.notEqual(run(root,'migrate-artifact-sheets','--apply').status,0);assert.equal(fs.readFileSync(path.join(root,'03 artefatos/Teste.md'),'utf8'),'Revisão posterior');});
test('estrutura não parseável bloqueia possível perda e mantém original',t=>{const root=fixture(t),before='## Ficha arqueológica\n\nTexto sem tabela.\n';write(root,'03 artefatos/Teste.md',before);assert.notEqual(run(root,'migrate-artifact-sheets').status,0);assert.equal(fs.readFileSync(path.join(root,'03 artefatos/Teste.md'),'utf8'),before);assert.notEqual(run(root,'migrate-artifact-sheets','--apply').status,0);});
test('pistas acumulam origens e sobrevivem a relatório vazio sem converter links',t=>{const root=fixture(t),manual='# Pistas\n\nPergunta curada que permanece.\n',note='[[03 artefatos/Futuro|Exemplo]]';write(root,'Pistas de pesquisa.md',manual);write(root,'03 artefatos/A.md',note);for(const origin of ['03 artefatos/A.md','03 artefatos/B.md']){write(root,'link-report.json',JSON.stringify({files:[{sourcePath:origin,unresolved:['03 artefatos/Futuro']}]}));assert.equal(run(root,'consolidate-unresolved-links').status,0);assert.equal(run(root,'consolidate-unresolved-links','--apply').status,0);}const accumulated=fs.readFileSync(path.join(root,'Pistas de pesquisa.md'),'utf8');assert.ok(accumulated.startsWith(manual));assert.ok(accumulated.includes('03 artefatos/A.md'));assert.ok(accumulated.includes('03 artefatos/B.md'));write(root,'link-report.json','{"files":[]}');assert.equal(run(root,'consolidate-unresolved-links').status,0);assert.equal(run(root,'consolidate-unresolved-links','--apply').status,0);assert.equal(fs.readFileSync(path.join(root,'Pistas de pesquisa.md'),'utf8'),accumulated);assert.equal(fs.readFileSync(path.join(root,'03 artefatos/A.md'),'utf8'),note);});
test('índice exclui publicar false e identifica links ambíguos sem escolher um destino',t=>{const root=fixture(t);write(root,'03 artefatos/Privado.md','---\ntitle: Privado\npublicar: false\n---\nSegredo fora do catálogo');write(root,'01 conceitos/A.md','---\ntitle: Igual\n---\nA');write(root,'02 variaveis/B.md','---\ntitle: Igual\n---\nB');write(root,'03 artefatos/Publico.md','---\nstatus: rascunho\n---\n[[Igual]] [[Inexistente]] [[03 artefatos/Privado]]');assert.equal(run(root,'build-search-index').status,0);const index=JSON.parse(fs.readFileSync(path.join(root,'search-index.json'))),report=JSON.parse(fs.readFileSync(path.join(root,'link-report.json')));assert.ok(!JSON.stringify(index).includes('Segredo fora do catálogo'));assert.equal(index.articleCount,3);assert.equal(report.ambiguousLinkCount,1);assert.equal(report.brokenLinkCount,1);const publicArticle=index.articles.find(a=>a.fileTitle==='Publico');assert.equal(publicArticle.status,'rascunho');assert.deepEqual(publicArticle.related,[]);});
test('gate bloqueia schema/links/perda, mas capitalização e rede permanecem avisos',t=>{const root=fixture(t);write(root,'templates/template-artefato.md',sheet(artifactFields));write(root,'editorial-report.json',JSON.stringify({schemaVersion:2,candidateCount:20,legacyArtifactFiles:[]}));write(root,'network-report.json','{"issueCount":10}');write(root,'link-report.json','{"files":[],"ambiguousFiles":[]}');assert.equal(run(root,'validate-publication').status,0);write(root,'link-report.json','{"files":[{"sourcePath":"A.md","unresolved":["X"]}],"ambiguousFiles":[{"sourcePath":"A.md","ambiguous":[{"target":"Y","candidates":["B","C"]}]}]}');assert.notEqual(run(root,'validate-publication').status,0);write(root,'link-report.json','{"files":[],"ambiguousFiles":[]}');write(root,'.review/migrate-artifact-sheets/manifest.json','{"losses":[{"sourcePath":"A.md","detail":"Valor perdido"}]}');assert.notEqual(run(root,'validate-publication').status,0);fs.rmSync(path.join(root,'.review'),{recursive:true});write(root,'templates/template-artefato.md',sheet(artifactFields.slice(0,26)));assert.notEqual(run(root,'validate-publication').status,0);});
test('recupera registros arquivados pelo migrador antigo sem apagar evidência ou inferir valores',t=>{const root=fixture(t);const names=[...seven],normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();const archive='Registros adicionais preservados da ficha anterior: '+names.map(name=>normalize(name)+': Registro literal '+name).join('; ');let before=sheet(artifactFields);for(const name of names)before=before.replace(`Valor de ${name} com [[Destino\\|alias]]`,'Ainda não explicitado.');before=before.replace('Valor de Consequências inesperadas com [[Destino\\|alias]]',archive);write(root,'03 artefatos/Teste.md',before);assert.equal(run(root,'migrate-artifact-sheets').status,0);assert.equal(run(root,'migrate-artifact-sheets','--apply').status,0);const after=fs.readFileSync(path.join(root,'03 artefatos/Teste.md'),'utf8');assert.ok(after.includes(archive));for(const name of names)assert.ok(after.includes(`| **${name}** | Registro literal ${name} |`));assert.equal(run(root,'migrate-artifact-sheets').status,0);assert.equal(JSON.parse(fs.readFileSync(path.join(root,'.review/migrate-artifact-sheets/manifest.json'))).changes.length,0);});
