export const schemaVersion = 2;
export const artifactFields = [
  ["Artefato", ["artefato", "nome do artefato"]],
  ["Período", ["periodo", "periodo aproximado", "ano aproximado"]],
  ["Autoria", ["autoria", "pessoas ou equipes envolvidas", "pessoas/equipes envolvidas", "criador", "criadores"]],
  ["Produto ou contexto", ["produto ou contexto", "produto ou contexto onde apareceu", "produto onde apareceu", "contexto onde apareceu"]],
  ["Tipo(s) de design", ["tipo(s) de design", "tipos de design", "tipo de design"]],
  ["Empresas ou instituições relacionadas", ["empresas ou instituições relacionadas", "empresas relacionadas", "instituições relacionadas"]],
  ["Problema original", ["problema original", "problema que resolvia"]],
  ["Mundo antes", ["mundo antes", "mundo antes da inovacao"]],
  ["Invenção", ["invencao"]],
  ["Refinamento", ["refinamento"]],
  ["Popularização", ["popularizacao"]],
  ["Padronização", ["padronizacao"]],
  ["Hipótese de design", ["hipotese de design"]],
  ["Promessa", ["promessa"]],
  ["Comportamento aproveitado", ["comportamento aproveitado"]],
  ["Comportamento produzido", ["comportamento produzido", "comportamento criado", "comportamento criado ou normalizado"]],
  ["Relação de poder", ["relacao de poder"]],
  ["Consequências inesperadas", ["consequencias inesperadas", "consequencia inesperada"]],
  ["Destino ou transformação posterior", ["destino ou transformacao posterior", "destino do artefato", "transformacao posterior"]],
  ["Futuro prometido", ["futuro prometido"]],
  ["Futuro produzido", ["futuro produzido"]],
  ["Quando a promessa virou expectativa", ["quando a promessa virou expectativa"]],
  ["Futuro tornado mais provável", ["futuro tornado mais provavel"]],
  ["Descendentes possíveis", ["descendentes possiveis"]],
  ["Novo problema produzido pelo sucesso", ["novo problema produzido pelo sucesso"]],
  ["Conceitos relacionados", ["conceitos relacionados"]],
  ["Variáveis relacionadas", ["variaveis relacionadas"]],
  ["Genealogia", ["genealogia", "genealogias"]],
  ["Percurso(s)", ["percurso(s)", "percursos"]],
  ["Parentes", ["parentes", "artefatos relacionados", "artefatos relacionados para estudos futuros"]],
  ["Leituras-chave", ["leituras-chave", "leituras chave", "leituras"]],
  ["Princípio de design revelado", ["principio de design revelado", "principio revelado", "principio de design"]],
  ["Questão em aberto", ["questao em aberto", "perguntas em aberto", "questões em aberto"]]
];
export function normalizeField(text) { return text.replace(/\*\*/g, "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().trim(); }
